# This is a basic workflow to help you get started with Actions

name: Check files added

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Test changed-files
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: 'src/stacks/'
      
      - name: Run changed-files with defaults on the src/stacks dir
        id: changed-files-for-src_stacks
        uses: tj-actions/changed-files@v29.0.0
        with:
          path: src/stacks

      - name: List all added files in src/stacks dir
        run: |
          for file in ${{ steps.changed-files-for-src_stacks.outputs.added_files }}; do
            echo "$file was added"
          done
